#!/bin/bash
echo -e "\e[1;34m"plees waitt ...


scan1='1'
while [ $? -eq 1 ]
do
ping -a -c 1 -f 192.168.$scan1.1 &>/dev/null
scan1=$((scan1+1))
done


scan='1'
echo -e "\e[1;35m" [OK]
for i in {1..999999}
do
ping -a -c 1 192.168.1.$scan &>/dev/null


if [ $? -eq 0 ]
then
echo 
echo -e "\e[1;33m"---------------------------------------------------------------------- 
echo -e "\e[1;31m"192.168.$scan1.$scan 
nslookup 192.168.$scan1.$scan                                                                            
echo -e "\e[1;33m"---------------------------------------------------------------------- 
echo
fi
scan=$((scan+1))

done
