#!/bin/bash

echo -e "\e[1;34m"plees waitt ...

scan1='1'
while [ $? -ne "1" ]
do
timeout 0.7 ping -a -c 1 -i 0.1-f 192.168.$scan1.1 &>/dev/null



if [ $? -eq 0 ]
then
   scan='1'
   for i in {1..2555}
   do
   timeout 0.67 ping -a -c 1 -i 0.1 -f 192.168.$scan1.$scan &>/dev/null
        	if [ $? -eq 0 ]
		then
		echo -e "\e[1;35m"_________________________________________________________________
		echo -e "\e[1;31m"
                echo 192.168.$scan1.$scan
		nslookup 192.168.$scan1.$scan
	        echo -e "\e[1;35m"_________________________________________________________________
		echo
		fi
   scan=$((scan+1))
   done
fi

scan1=$((scan1+1))

done
